# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]

-   repo: builtin
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: |
          (?x)^(
            taskiq_dashboard/api/static/.*|
            uv.lock
          )$
    -   id: end-of-file-fixer

-   repo: https://github.com/crate-ci/typos
    rev: v1.42.1
    hooks:
      - id: typos
        exclude: taskiq_dashboard/api/static/htmx.js

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: [
            '--exclude-files', 'bun.lock',
            '--exclude-files', 'taskiq_dashboard/api/static/htmx.js',
            '--exclude-lines', 'look_in_vault',
            '--exclude-lines', 'taskiq_postgres',
            '--exclude-lines', 'postgresql://postgres:postgres@localhost:5432/postgres',
        ]

-   repo: local
    hooks:
    -   id: ruff
        name: Ruff
        entry: make ruff
        language: system
        require_serial: true
        verbose: true
        pass_filenames: false

    -   id: ty
        name: Type check
        entry: make ty
        language: system
        require_serial: true
        verbose: true
        pass_filenames: false

    -   id: zizmor
        name: zizmor
        language: system
        entry: uv run --active --frozen zizmor .
        files: ^\.github
        require_serial: true
        verbose: true
        pass_filenames: false
